### ISSUE TITLE
[bug] NEO Coolcam Roller Shutter - Curtain Switch - NAS-SC03ZE-2-T-V3 disappears

### ISSUE THREAD

**Issue by Goldwing1973** [zwave-js/node-zwave-js#4592]
**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: zwavejs2mqtt: 4.5.0
zwave-js version: zwave-js: 7.7.0

### Describe the bug

I have 3 NEO Coolcam Roller Shutter - Curtain Switch - NAS-SC03ZE-2-T-V3’s
One is presumed dead by Z-WaveJS because it isn’t powered on/not connected and is still visible in the control panel.
But the other 2 just vanished, like they where Excluded.
It’s not the first time it happened, a couple of months ago it happened before. 

### To Reproduce

There are no steps to actually reproduce it, it just happens.

**Comment by pawkakol1** [comment]
The same issue. NAS-SC03ZE-2-T-V3 randomly disapears from zwave js. Sometimes it is 1 mounth sometimes 1 day. It looks like excluded device, no offline device and no entites availible in Hassio (Home Assistant OS). Device resets up and down states too. Durring adding it again it gets new node number. 
Unfortunately I didn't get any logs, because on Hassio the log vew has to be opened all the timer, otherwise subscription is unsubscribed.
I will try to collect any logs.

**Comment by Goldwing1973** [comment]
> 
> 
> The same issue. NAS-SC03ZE-2-T-V3 randomly disapears from zwave js. Sometimes it is 1 mounth sometimes 1 day. It looks like excluded device, no offline device and no entites availible in Hassio (Home Assistant OS). Device resets up and down states too. Durring adding it again it gets new node number. Unfortunately I didn't get any logs, because on Hassio the log vew has to be opened all the timer, otherwise subscription is unsubscribed. I will try to collect any logs.

I'm also still having the problem, i tried collecting logs, but the time between noticing and the disapearing was to long to find anything in the logs
And because it's also getting colder now the use of the sunscreen is minimal

**Comment by robertsLando** [comment]
Sorry guys but without any log I cannot help here. @AlCalzone do you know if this device is known to have problems?

**Comment by AlCalzone** [comment]
Nope

**Comment by Goldwing1973** [comment]
@robertsLando Do you know what i have to look for in the logs? Last time it took me hours to scroll thru the logs but could not find anything (or i missed it) that looks like a disconnection/removal

**Comment by AlCalzone** [comment]
Not sure, but having the logs means I can take a look.

**Comment by robertsLando** [comment]
@Goldwing1973 We neeed zwavejs logs, just export the file from store and we will take a look at them, usually a normal user cannot find the problem by watching to them

**Comment by Goldwing1973** [comment]
> @Goldwing1973 We neeed zwavejs logs, just export the file from store and we will take a look at them, usually a normal user cannot find the problem by watching to them

I have a 100mb .ZIP file with logs, is there any personal information in those logs I should be aware of or can I just post the file here?

**Comment by AlCalzone** [comment]
depends if you were setting user codes or something. You can upload it somewhere though and send me the link via e-mail.

**Comment by Goldwing1973** [comment]
> 
> 
> depends if you were setting user codes or something. You can upload it somewhere though and send me the link via e-mail.

You have mail.

**Comment by Goldwing1973** [comment]
Oh, and before i forget, i have 3 NAS-SC03ZE-2-T-V3's
One is presumed dead by Z-WaveJS, but that's because it still needs installation in the wall. (node 38)
One is Alive, (node 68) but has dissapeared also a couple of times
And the last one, is gone (Woonkamer Zonnescherm) and havn't re-added it.

**Comment by AlCalzone** [comment]
Ok, I didn't find anything definite in there. Because of the log rotation, the driver logs only go back 7 days. So I see you added a node 69, but I didn't see where 68 vanished. You might want to up the loglevel here to debug to catch any commands that could cause the node to be removed.

In contrast, your 8 million lines application log goes back till May. That's probably a bit overkill. The most indications of removed nodes are probably attempts of **Remove Failed Node**, but that is already a month ago:
```
2021-09-29 11:39:04.041 INFO ZWAVE: Node 67 is now dead
2021-09-29 11:39:05.856 INFO ZWAVE: Node 21: metadata updated: 49-0-Power
2021-09-29 11:39:05.857 INFO ZWAVE: Node 21: value updated: 49-0-Power 0.9 => 0.7
2021-09-29 11:39:10.230 INFO ZWAVE: ValueRemoved: 114-0-manufacturerId from node 67
... a bunch ...
2021-09-29 11:39:10.253 INFO ZWAVE: Node 67: value removed: 112-0-5
2021-09-29 11:39:10.254 INFO ZWAVE: Node 67: metadata updated: 112-0-5
2021-09-29 11:39:10.260 INFO ZWAVE: Node 67: removed
2021-09-29 11:39:10.261 INFO ZWAVE: Node removed 67
```
and the same for Nodes 55 and 62 earlier.

I do see a couple of dropped commands which look like something is querying the controller with commands it doesn't understand or make sense (e.g. Multilevel Sensor Get Supported Scales). Do you have a secondary controller by any chance which is capable of including/excluding nodes?

**Comment by Goldwing1973** [comment]
> . Do you have a secondary controller by any chance which is capable of including/excluding nodes?

Actually, i do.
I have a second Aeonlabs z-wave stick and a un-used thin client with Debian 11 on it.
For testing purposes i can try to re-add the NAS-SC03ZE-2-T-V3 and only that device to the second controller and set logging to debug (or silly?)

What is best? installing it using Docker? or PKG?

And, 67 is the dissapeared NAS-SC03ZE-2-T-V3 (Woonkamer Zonnescherm)

**Comment by AlCalzone** [comment]
> I have a second Aeonlabs z-wave stick

No, I meant if there is a secondary controller included in the network. Some remotes are capable of doing inclusion/exclusion, so you **might** have accidentally performed an exclusion.

The above log, especially 67 looks more like an automation that removes dead nodes or the **Remove Failed Node** function. 

However, the fact that the node is excluded only seconds after it is marked dead seems fishy. This means that the device could have sent a **Device Reset Locally Notification**, which means that the device has been physically reset. In response to that, the controller removes it from the network because it is de facto no longer a part of it.
I've had a user whose switches went missing like this a couple of times. In the end, it was a cable that kept pressing the device button and reset it.

**Comment by Goldwing1973** [comment]
, it was a cable that kept pressing the device button and reset it.

The only way to reset it is bij pressing the center button for 10 seconds, and I already tried to eliminate that option by gluing a piece of plastic over the center button so it couldn’t be touched.
But still it disappeared.
![image](https://user-images.githubusercontent.com/67235461/139035039-8519ebf3-055f-4e9a-ac0c-6817013aa7cb.jpeg)

**Comment by AlCalzone** [comment]
Then I guess you need to catch when it happens in a driver log (loglevel debug).

**Comment by Goldwing1973** [comment]
Because of the log rotation, the driver logs only go back 7 days.

Can i extend the 7 days to say 30 days?

**Comment by AlCalzone** [comment]
You could copy them every 7 days. Or locate the file `node_modules/@zwave-js/core/build/log/shared.js` (not sure where exactly it is in the container) and edit line 219:
```diff
-            maxFiles: "7d",
+            maxFiles: "30d",
```

**Comment by wube1** [comment]
@pawkakol1 Hi pawkakol1, sorry to fish you oout here like that, i have a question regarding some other branch you were contributing to. May I ask if there is a way to contact you with priv messages? Thanks a lot in advance for your reply.

**Comment by pawkakol1** [comment]
@wube1 go a head. My e-mail is visible

**Comment by AlCalzone** [comment]
Since we haven't seen any new info regarding the original issue, I'm going to close this. Feel free to reopen if you can capture the issue happening in a log.

**Comment by Goldwing1973** [comment]
Nearly a year later, but I’m going to trash the devices.
I’m reading more and more from others having the same problem, apparently the device is buggy as hell and invokes a reset on its own from time to time.
I now ordered a Fibaro Walli roller shutter, if that works better I’ll replace them all.
@AlCalzone , thank you for your efforts.

**Comment by pawkakol1** [comment]
I noticed, that device resets itself if on network are some baterry powered devices, and one of such device will discharge. Earlier I didnt pay attention on discharged devices, and my NAS-SC03ZE-2-T-V3 device was resetting every few days. Since I noticed association with baterry discharging, I started to charge them before they were discharged about 3 mounths ago. Up today I havent had any situation of reset NAS-SC03ZE-2-T-V3 device, and I hope it will be last as long as possible.
I suppose, that non-baterry powered, but powered down devices will affect likewise.

**Comment by AlCalzone** [comment]
> I suppose, that non-baterry powered, but powered down devices will affect likewise.

If that's the case, there is something seriously wrong with the device.

**Comment by Goldwing1973** [comment]
> > I suppose, that non-baterry powered, but powered down devices will affect likewise.
> 
> If that's the case, there is something seriously wrong with the device.

If you want, i can send you one (at my expence) to fool around with it, and i don't need/want it back.

**Comment by Goldwing1973** [comment]
One last attempt...
I installed HA + Z-WaveJS2mqtt on a Pi3, plugged a factory reset Aeon Labs ZW090 stick in it and added the curtain switch.
After adding i pressed some buttons and then i kept on pressing the down button, and yes, the device also registered my finger on the center button and after 10 seconds or so, it factory resetted.
But... i was NOT removed from Z-WaveJS, it remained as a DEAD node after i pinged it.
I;ve attached a log (silly level), could you taken one more look @AlCalzone ? maybee you can see why it is not removed from Z-WaveJS this time.
[zwavejs2mqtt_2022-05-07.log](https://github.com/zwave-js/zwavejs2mqtt/files/8645139/zwavejs2mqtt_2022-05-07.log)

**Comment by AlCalzone** [comment]
That's not a driver log, so I can't tell. Probably didn't send the reset notification this time.

**Comment by robertsLando** [comment]
@AlCalzone Maybe it's worth to add a comment on this device config file to warn about this?

**Comment by AlCalzone** [comment]
Yeah, I guess.
